// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5lIld5ll1eY8p7XwN7vgu6r6tpqswGA',
    appId: '1:579845479812:web:d0042dfa7660e658a4d1d1',
    messagingSenderId: '579845479812',
    projectId: 'garage-auto-app-001',
    authDomain: 'garage-auto-app-001.firebaseapp.com',
    storageBucket: 'garage-auto-app-001.appspot.com',
    measurementId: 'G-PDL6H5JPG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkeELPvz0n2pNreg0gG_SAqohqKLo2fuQ',
    appId: '1:579845479812:android:96ac08b7c5371da7a4d1d1',
    messagingSenderId: '579845479812',
    projectId: 'garage-auto-app-001',
    storageBucket: 'garage-auto-app-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIj-EcC1DZEzDk8Xuq2HIq5SFNbewjniM',
    appId: '1:579845479812:ios:d617c7fb78649c0da4d1d1',
    messagingSenderId: '579845479812',
    projectId: 'garage-auto-app-001',
    storageBucket: 'garage-auto-app-001.appspot.com',
    androidClientId: '579845479812-k89edvuhtisg9ssarr3blkeh46195ima.apps.googleusercontent.com',
    iosClientId: '579845479812-qb3ejvkp8lmv2jr0hprtgpg93grnse4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.garageAutoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIj-EcC1DZEzDk8Xuq2HIq5SFNbewjniM',
    appId: '1:579845479812:ios:d617c7fb78649c0da4d1d1',
    messagingSenderId: '579845479812',
    projectId: 'garage-auto-app-001',
    storageBucket: 'garage-auto-app-001.appspot.com',
    androidClientId: '579845479812-k89edvuhtisg9ssarr3blkeh46195ima.apps.googleusercontent.com',
    iosClientId: '579845479812-qb3ejvkp8lmv2jr0hprtgpg93grnse4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.garageAutoApp',
  );
}
